const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Read environment variables
const config = {
  GEMINI_API_KEY: process.env.GEMINI_API_KEY
};

// Generate config.js file for client-side use
const configContent = `// Auto-generated configuration file
// Do not edit this file directly, edit .env instead and run npm run build

window.CONFIG = ${JSON.stringify(config, null, 2)};
`;

// Write the config file
fs.writeFileSync(path.join(__dirname, '..', 'config.js'), configContent);
console.log('Configuration file generated successfully!');